Add GH Action for updating wiki.

diff --git a/.github/workflows/uncivbot.yml b/.github/workflows/uncivbot.yml
--- a/.github/workflows/uncivbot.yml
+++ b/.github/workflows/uncivbot.yml
@@ -5,6 +5,56 @@ on:
   workflow_dispatch:
 
 jobs:
+  update_wiki:
+    if: github.event.name == 'issue_comment' && github.event.comment.body == 'update wiki'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Update Wiki.
+        # Compare to https://github.com/SwiftDocOrg/github-wiki-publish-action/blob/v1/entrypoint.sh
+        run: |
+          set -euo pipefail # Immediate exit on command errors and unset variables.
+          set -x # Print out each executed command.
+
+          for REQUIRED_ENV_VAR in GITHUB_ACTOR GITHUB_SERVER_URL GITHUB_REPOSITORY GH_TOKEN CODE_DIR WIKI_DIR WIKI_IN_CODE_REPO PR_AUTHOR PR_TITLE PR_NUMBER; do
+            if [ -z "$(eval "echo \$$REQUIRED_ENV_VAR")" ]; then
+              echo "ERROR: \$$REQUIRED_ENV_VAR is not set."
+              exit 1
+            fi
+          done
+
+          CODE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
+          WIKI_URL="https://${GH_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.wiki.git"
+
+          git clone "$CODE_URL" "$CODE_DIR"
+          git clone "$WIKI_URL" "$WIKI_DIR"
+
+          rsync -ac --delete --exclude '.git*' "${CODE_DIR}${WIKI_IN_CODE_REPO}" "WIKI_DIR/"
+
+          cd "WIKI_DIR"
+
+          for f in *.md; do
+           echo "Formatting $f links."
+           # Convert AS/GH code browser inter-page links to GH Wiki links by stripping `.md` extensions.
+           sed -ie 's|\(](\./[^)]*\)\.md|\1|g' "$f"
+           # Convert AS/GH code browser repo file links to GH Wiki links by prepending repo browser to absolute links.
+           sed -ie 's|](/|](https://github.com/${GITHUB_REPOSITORY}/tree/master/|g' "$f"
+          done
+
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+
+          git add .
+          git commit -m "${PR_AUTHOR}: ${PR_TITLE} (#${PR_NUMBER})"
+          git push
+        env:
+          GH_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
+          CODE_DIR: CodeRepo
+          WIKI_DIR: WikiRepo
+          WIKI_IN_CODE_REPO: /docs/wiki
+          PR_AUTHOR: ${{ github.event.issue.user.login }}
+          # I think directly putting these in the script would let quotes in PR title break the script.
+          PR_TITLE: ${{ github.event.issue.title }}
+          PR_NUMBER: ${{ github.event.issue.number }}
   summary:
     if: github.event_name == 'issue_comment' && github.event.comment.body == 'summary'
     runs-on: ubuntu-latest
