Add GH Action for updating wiki.

diff --git a/.github/workflows/uncivbot.yml b/.github/workflows/uncivbot.yml
--- a/.github/workflows/uncivbot.yml
+++ b/.github/workflows/uncivbot.yml
@@ -5,6 +5,87 @@ on:
   workflow_dispatch:
 
 jobs:
+  update_wiki:
+    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == 'update wiki'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Update Wiki.
+        # Compare to https://github.com/SwiftDocOrg/github-wiki-publish-action/blob/v1/entrypoint.sh
+        run: |
+          echo "$EVENT_CONTEXT"
+
+          set -euo pipefail # Immediate exit on command errors and unset variables.
+          # set -x # Print out each executed command. THIS MAY LEAK THE PERSONAL ACCESS TOKEN SECRET VIA $GH_TOKEN and $WIKI_URL (though AFAICT GH is sanitizing it)!
+
+          for REQUIRED_ENV_VAR in GITHUB_ACTOR GITHUB_SERVER_URL GITHUB_REPOSITORY GH_TOKEN CODE_DIR WIKI_DIR WIKI_IN_CODE_REPO PR_AUTHOR PR_TITLE PR_NUMBER; do
+            if [ -z "$(eval "echo \$$REQUIRED_ENV_VAR")" ]; then
+              echo "ERROR: \$$REQUIRED_ENV_VAR is not set."
+              exit 1
+            fi
+          done
+
+          if [ "${PR_MERGEDAT}" = null ]; then
+            echo "ERROR: Pull request must be merged."
+            exit 1
+          fi
+
+          CODE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
+          WIKI_URL="https://${GH_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.wiki.git"
+
+          echo "Cloning repository: $CODE_URL"
+          git clone "$CODE_URL" "$CODE_DIR"
+          echo "Cloning Wiki."
+          git clone "$WIKI_URL" "$WIKI_DIR"
+
+          echo 'Running `rsync`.'
+          rsync -avc --delete --exclude '.git*' "${CODE_DIR}${WIKI_IN_CODE_REPO}/" "$WIKI_DIR/"
+          # …The trailing slashes here are very important! Otherwise it will copy/target the directory, instead of its contents.
+
+          echo "Formatting Markdown files in $WIKI_DIR."
+          cd "$WIKI_DIR"
+
+          for f in *.md; do
+            if [ -e "$f" ]; then
+              echo "Formatting $f links."
+              # Convert AS/GH code browser inter-page links to GH Wiki links by stripping `.md` extensions.
+              sed -ie 's|\(](\./[^)]*\)\.md|\1|g' "$f"
+              # Convert AS/GH code browser repo file links to GH Wiki links by prepending repo browser to absolute links.
+              sed -ie 's|](/|](https://github.com/${GITHUB_REPOSITORY}/tree/master/|g' "$f"
+            else # When glob produces no matches, you just get the glob pattern instead.
+              echo "Skipping non-existent file $f."
+            fi
+          done
+
+          echo "Finished formatting Markdown files."
+
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+
+          echo "Wiki files:"
+          tree
+          echo "Adding files to Git."
+          git add .
+          echo "Git cached diff stats:"
+          git diff --stat --cached | cat # IDK If Git might try to enter the interactive viewer without a pipe output. Probably not, but play it safe.
+          echo "Committing changes."
+          git commit -m "${PR_AUTHOR}: ${PR_TITLE} (${PR_URL})" # Deliberately not passing --allow-empty, as that should probably error.
+          echo "Pushing changes."
+          git push -f
+          #git push -f --set-upstream "$WIKI_URL" master # Should be the same since we cloned from the URL, just more explicit.
+          echo "Done."
+        env:
+          GH_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
+          CODE_DIR: CodeRepo
+          WIKI_DIR: WikiRepo
+          WIKI_IN_CODE_REPO: /docs/wiki
+          EVENT_CONTEXT: ${{ toJSON(github) }}
+          # Dump for debug.
+          PR_MERGEDAT: ${{ github.event.issue.pull_request.merged_at }}
+          PR_AUTHOR: ${{ github.event.issue.user.login }}
+          # I think directly putting these in the script would let quotes in PR title break the script. Set environment variables so Bash can take care of the substitution.
+          PR_TITLE: ${{ github.event.issue.title }}
+          #PR_NUMBER: ${{ github.event.issue.number }}
+          PR_URL: ${{ github.event.issue.html_url }}
   summary:
     if: github.event_name == 'issue_comment' && github.event.comment.body == 'summary'
     runs-on: ubuntu-latest
